from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', RedirectView.as_view(url='/home', permanent=False)),
    path('home', views.home, name='home'),
    path('login/', views.custom_login, name='login'),
    path('logout/', views.custom_logout, name='logout'),
    path('incident/<int:id>/overview', views.overview, name='overview'),
    path('incident/<int:id>/timeline', views.timeline, name='timeline'),
    path('incident/<int:id>/activity', views.activity, name='activity'),
    path('incident/<int:id>/impacts', views.impacts, name='impacts'),
    path('incident/<int:id>/join', views.join, name='join'),
    path('incident/<int:id>/tasks', views.tasks, name='tasks'),
    path('incident/<int:id>/notes', views.notes, name='notes'),
    path('incident/<int:id>/settings', views.incident_settings, name='incident_settings'),
    path('incident/<int:id>/report', views.report, name='report'),
    path('incident/<int:id>/iocs', views.iocs, name='iocs'),
    path('about', views.about, name='about'),
    path('settings', views.settings_view, name='settings'),
    path('incident/create', views.create_incident, name='create_incident'),
    path('incident/<int:id>/invite', views.incident_invite, name='incident_invite'),
    path('api/incident/<int:id>/regenerate-invite/', views.regenerate_invite, name='regenerate_invite'),
    path('profile', views.profile, name='profile'),
    path('api/update-profile/', views.update_profile, name='update_profile'),
    path('api/incident/<int:id>/update/', views.update_incident, name='update_incident'),
    path('api/incident/<int:id>/update-role/', views.update_role, name='update_role'),
    path('api/incident/<int:id>/delete-role/', views.delete_role, name='delete_role'),
    path('api/incident/<int:id>/download-json/', views.download_incident_json, name='download_incident_json'),
    path('api/incident/<int:id>/download-markdown/', views.download_incident_markdown, name='download_incident_markdown'),
    path('api/incident/<int:id>/download-pdf/', views.download_incident_pdf, name='download_incident_pdf'),
    path('api/incident/<int:id>/report-preview/', views.report_preview, name='report_preview'),
    path('api/incident/<int:id>/download-word/', views.download_incident_word, name='download_incident_word'),
    path('api/incident/<int:id>/download-csv/', views.download_incident_csv, name='download_incident_csv'),
    path('api/incident/<int:id>/download-html/', views.download_incident_html, name='download_incident_html'),
    path('api/incident/<int:id>/send-message/', views.send_message, name='send_message'),
    path('api/incident/<int:id>/get-messages/', views.get_messages, name='get_messages'),
    path('api/incident/<int:id>/add-ioc/', views.add_ioc, name='add_ioc'),
    path('api/incident/<int:id>/import-iocs/', views.import_iocs, name='import_iocs'),
    path('api/incident/<int:id>/update-ioc/', views.update_ioc, name='update_ioc'),
    path('api/incident/<int:id>/delete-ioc/', views.delete_ioc, name='delete_ioc'),
    path('api/incident/<int:id>/iocs/', views.get_all_iocs, name='get_all_iocs'),
    path('api/incident/<int:id>/add-note/', views.add_note, name='add_note'),
    path('api/incident/<int:id>/update-note/', views.update_note, name='update_note'),
    path('api/incident/<int:id>/delete-note/', views.delete_note, name='delete_note'),
    path('api/incident/<int:id>/upload-file/', views.upload_file, name='upload_file'),
    path('api/incident/<int:id>/delete-file/', views.delete_file, name='delete_file'),
    path('api/incident/<int:id>/add-task/', views.add_task, name='add_task'),
    path('api/incident/<int:id>/update-task/', views.update_task, name='update_task'),
    path('api/incident/<int:id>/delete-task/', views.delete_task, name='delete_task'),
    path('api/incident/<int:id>/add-action/', views.add_action, name='add_action'),
    path('api/incident/<int:id>/import-actions/', views.import_actions, name='import_actions'),
    path('api/incident/<int:id>/update-action/', views.update_action, name='update_action'),
    path('api/incident/<int:id>/get-action/<int:action_id>/', views.get_action, name='get_action'),
    path('api/incident/<int:id>/delete-action/', views.delete_action, name='delete_action'),
    path('api/incident/<int:id>/get-ioc/<int:ioc_id>/', views.get_ioc, name='get_ioc'),
    path('api/incident/<int:id>/get-impact/<int:impact_id>/', views.get_impact, name='get_impact'),
    path('api/incident/<int:id>/update-impact/', views.update_impact, name='update_impact'),
    path('api/incident/<int:id>/delete-impact/', views.delete_impact, name='delete_impact'),
    path('api/incident/<int:id>/audit-logs/', views.get_audit_logs, name='get_audit_logs'),
    path('api/incident/<int:id>/audit-logs/export/', views.export_audit_logs, name='export_audit_logs'),
    path('api/incident/<int:id>/ai-rephrase/', views.ai_rephrase, name='ai_rephrase'),
    path('api/categories/', views.list_categories, name='list_categories'),
    path('api/categories/create/', views.create_category, name='create_category'),
    path('api/incident/<int:id>/add-category/', views.add_incident_category, name='add_incident_category'),
    path('api/incident/<int:id>/remove-category/', views.remove_incident_category, name='remove_incident_category'),
    path('api/platform-settings/', views.save_platform_settings, name='save_platform_settings'),
    path('api/cti-providers/', views.save_cti_provider, name='save_cti_provider'),
    path('api/cti-providers/delete/', views.delete_cti_provider, name='delete_cti_provider'),
    path('api/incident/<int:id>/ioc/<int:ioc_id>/reputation/', views.ioc_reputation, name='ioc_reputation'),
    path('api/incident/<int:id>/ioc/<int:ioc_id>/reputation/refresh/', views.refresh_ioc_reputation, name='refresh_ioc_reputation'),
    path('incident/<int:id>/warroom', views.warroom, name='warroom'),
    path('api/incident/<int:id>/warroom-data/', views.warroom_data, name='warroom_data'),

    # Merge
    path('api/incident/<int:id>/merge/', views.merge_incident, name='merge_incident'),

    # Threat Intelligence Hub
    path('threat-intel', views.threat_intel, name='threat_intel'),
    path('api/threat-intel/iocs/', views.api_ti_iocs, name='api_ti_iocs'),
    path('api/threat-intel/stats/', views.api_ti_stats, name='api_ti_stats'),
    path('api/threat-intel/heatmap/', views.api_ti_heatmap, name='api_ti_heatmap'),
    path('api/threat-intel/pivot/', views.api_ti_pivot, name='api_ti_pivot'),
    path('api/threat-intel/export/csv/', views.api_ti_export_csv, name='api_ti_export_csv'),
    path('api/threat-intel/export/json/', views.api_ti_export_json, name='api_ti_export_json'),
    path('api/threat-intel/export/pdf/', views.api_ti_export_pdf, name='api_ti_export_pdf'),
    path('api/threat-intel/campaign-stats/', views.api_ti_campaign_stats, name='api_ti_campaign_stats'),
    path('api/threat-intel/export/campaign-pdf/', views.api_ti_campaign_report_pdf, name='api_ti_campaign_report_pdf'),

    # Campaigns
    path('api/campaigns/', views.api_campaigns_list, name='api_campaigns_list'),
    path('api/campaigns/create/', views.api_campaign_create, name='api_campaign_create'),
    path('api/campaigns/<int:campaign_id>/update/', views.api_campaign_update, name='api_campaign_update'),
    path('api/campaigns/<int:campaign_id>/delete/', views.api_campaign_delete, name='api_campaign_delete'),
    path('api/campaigns/<int:campaign_id>/add-incident/', views.api_campaign_add_incident, name='api_campaign_add_incident'),
    path('api/campaigns/<int:campaign_id>/remove-incident/', views.api_campaign_remove_incident, name='api_campaign_remove_incident'),
]
# Serve media files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
