# Generated by Django 4.0.3 on 2026-06-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencirt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='invite_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
