# Generated by Django 6.0.6 on 2026-06-21 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencirt', '0006_add_platform_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register'), ('SETTINGS_CHANGE', 'Settings Change'), ('ROLE_CHANGE', 'Role Change'), ('INCIDENT_CREATE', 'Incident Create'), ('INCIDENT_DELETE', 'Incident Delete'), ('USER_DELETE', 'User Delete'), ('CTI_CHANGE', 'CTI Change'), ('AI_CHANGE', 'AI Change'), ('OTHER', 'Other')], max_length=20)),
                ('object_type', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
