# Generated by Django 6.0.6 on 2026-06-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencirt', '0016_incident_external_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='genericioc',
            name='type',
            field=models.CharField(choices=[('IPADRESS', 'IP Address'), ('URL', 'URL'), ('DOMAIN', 'Domain'), ('NETWORK', 'Network / CIDR'), ('EMAIL', 'Email'), ('HASH', 'Hash'), ('FILE', 'File'), ('FILENAME', 'Filename'), ('ACCOUNT', 'Account'), ('PASSWORD', 'Password'), ('FOLDER', 'Folder'), ('SRC_PORT', 'Source Port'), ('DST_PORT', 'Destination Port'), ('DEVICE', 'Device'), ('ISP', 'Isp'), ('PERSON', 'Person'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
