# Generated by Django 4.0.3 on 2024-12-20 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('executive_summary', models.TextField()),
                ('business_impact', models.TextField(default='SOME STRING')),
                ('systems_impact', models.TextField(default='SOME STRING')),
                ('lessons_learned', models.TextField(default='SOME STRING')),
                ('technical_details', models.TextField(default='SOME STRING')),
                ('export_include_timeline', models.BooleanField(default=True)),
                ('export_include_iocs', models.BooleanField(default=True)),
                ('export_include_attachements', models.BooleanField(default=True)),
                ('starting_time', models.DateTimeField()),
                ('ending_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('time_to_detect', models.DurationField()),
                ('time_to_respond', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('iocs_shared', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('first_connection_time', models.DateTimeField(auto_now_add=True)),
                ('last_connection_time', models.DateTimeField(blank=True, null=True)),
                ('displayname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('incident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sharpcirt.incident')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_sent', to='sharpcirt.responder')),
            ],
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.TextField()),
                ('status', models.CharField(choices=[('COMPROMISED', 'Compromised'), ('POTENTIALLY_COMPROMISED', 'Potentially Compromised'), ('SAFE', 'Safe')], default='SAFE', max_length=30)),
                ('description', models.TextField()),
                ('ip', models.GenericIPAddressField()),
                ('type', models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public'), ('PUBLIC_OWNED', 'Public Owned')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_created', to='sharpcirt.responder')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='sharpcirt.incident')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_created', to='sharpcirt.responder'),
        ),
        migrations.AddField(
            model_name='incident',
            name='responders',
            field=models.ManyToManyField(related_name='incidents', to='sharpcirt.responder'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.TextField()),
                ('status', models.CharField(choices=[('COMPROMISED', 'Compromised'), ('POTENTIALLY_COMPROMISED', 'Potentially Compromised'), ('SAFE', 'Safe')], default='SAFE', max_length=30)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_created', to='sharpcirt.responder')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sharpcirt.incident')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.TextField()),
                ('status', models.CharField(choices=[('COMPROMISED', 'Compromised'), ('POTENTIALLY_COMPROMISED', 'Potentially Compromised'), ('SAFE', 'Safe')], default='SAFE', max_length=30)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_created', to='sharpcirt.responder')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='sharpcirt.incident')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
