# Generated by Django 4.0.3 on 2024-12-20 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericIoc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.TextField()),
                ('status', models.CharField(choices=[('COMPROMISED', 'Compromised'), ('POTENTIALLY_COMPROMISED', 'Potentially Compromised'), ('SAFE', 'Safe')], default='SAFE', max_length=30)),
                ('description', models.TextField()),
                ('value', models.TextField()),
                ('type', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genericioc_created', to='sharpcirt.responder')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genericioc', to='sharpcirt.incident')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='file',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='file',
            name='incident',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
