# Generated by Django 5.1.4 on 2024-12-22 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0002_genericioc_remove_file_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericioc',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genericiocs', to='sharpcirt.incident'),
        ),
        migrations.AlterField(
            model_name='genericioc',
            name='type',
            field=models.CharField(choices=[('FILE', 'File'), ('FILENAME', 'Filename'), ('ACCOUNT', 'Account'), ('PASSWORD', 'Password'), ('FOLDER', 'Folder'), ('HASH', 'Hash'), ('NETWORK', 'Network'), ('SRC_PORT', 'Source Port'), ('DST_PORT', 'Destination Port'), ('EMAIL', 'Email'), ('DEVICE', 'Device'), ('ISP', 'Isp'), ('PERSON', 'Person'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_created', to='sharpcirt.responder')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='sharpcirt.incident')),
            ],
        ),
    ]
