# Generated by Django 4.0.3 on 2026-06-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencirt', '0002_add_invite_code_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
