# Generated by Django 5.1.4 on 2024-12-22 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0004_user_incident_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericioc',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genericioc_created', to='sharpcirt.user'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_created', to='sharpcirt.user'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_created', to='sharpcirt.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_sent', to='sharpcirt.user'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_created', to='sharpcirt.user'),
        ),
    ]
