# Generated by Django 4.0.3 on 2025-01-02 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0005_alter_genericioc_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericioc',
            name='type',
            field=models.CharField(choices=[('IPADRESS', 'IP Address'), ('FILE', 'File'), ('FILENAME', 'Filename'), ('ACCOUNT', 'Account'), ('PASSWORD', 'Password'), ('FOLDER', 'Folder'), ('HASH', 'Hash'), ('NETWORK', 'Network'), ('SRC_PORT', 'Source Port'), ('DST_PORT', 'Destination Port'), ('EMAIL', 'Email'), ('DEVICE', 'Device'), ('ISP', 'Isp'), ('PERSON', 'Person'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.TextField()),
                ('status', models.CharField(choices=[('COMPROMISED', 'Compromised'), ('POTENTIALLY_COMPROMISED', 'Potentially Compromised'), ('SAFE', 'Safe')], default='SAFE', max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField()),
                ('type', models.CharField(choices=[('MALICIOUS', 'Malicious'), ('DEFENSIVE', 'Defensive'), ('MITIGATION', 'Mitigation'), ('COMMUNICATION', 'Communication'), ('ALERT', 'Alert'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_created', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='sharpcirt.incident')),
                ('iocs', models.ManyToManyField(related_name='actions', to='sharpcirt.responder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
