# Generated by Django 4.0.3 on 2025-01-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0006_alter_genericioc_type_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='iocs',
            field=models.ManyToManyField(related_name='actions', to='sharpcirt.genericioc'),
        ),
    ]
