# Generated by Django 4.0.3 on 2025-01-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0007_alter_action_iocs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='value',
        ),
        migrations.AddField(
            model_name='action',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
