# Generated by Django 4.0.3 on 2025-01-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0008_remove_action_value_action_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='responders',
        ),
        migrations.AddField(
            model_name='action',
            name='is_first_action_this_day',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Responder',
        ),
    ]
