# Generated by Django 5.1.4 on 2025-01-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0010_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priotity',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('URGENT', 'Urgent'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20),
        ),
    ]
