# Generated by Django 4.0.3 on 2025-01-04 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0011_remove_task_priotity_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='incident',
            name='leaders',
            field=models.ManyToManyField(related_name='incidents_leaders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='readers',
            field=models.ManyToManyField(related_name='incidents_readers', to=settings.AUTH_USER_MODEL),
        ),
    ]
