# Generated by Django 4.0.3 on 2026-06-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencirt', '0011_remove_reputation_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericioc',
            name='type',
            field=models.CharField(choices=[('IPADRESS', 'IP Address'), ('URL', 'URL'), ('NETWORK', 'Network / CIDR'), ('EMAIL', 'Email'), ('HASH', 'Hash'), ('FILE', 'File'), ('FILENAME', 'Filename'), ('ACCOUNT', 'Account'), ('PASSWORD', 'Password'), ('FOLDER', 'Folder'), ('SRC_PORT', 'Source Port'), ('DST_PORT', 'Destination Port'), ('DEVICE', 'Device'), ('ISP', 'Isp'), ('PERSON', 'Person'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
