# Generated by Django 4.0.3 on 2025-01-04 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0012_remove_user_role_incident_leaders_incident_readers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('INCIDENT_LEAD', 'Incident Lead'), ('RESPONDER', 'Responder'), ('READER', 'Reader')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='incident',
            name='leaders',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='readers',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='users',
        ),
        migrations.AddField(
            model_name='incident',
            name='user_roles',
            field=models.ManyToManyField(related_name='incidents', through='sharpcirt.UserRole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrole',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_roles', to='sharpcirt.incident'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'incident')},
        ),
    ]
