# Generated by Django 4.0.3 on 2025-01-04 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0013_userrole_remove_incident_leaders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='user_roles',
            field=models.ManyToManyField(related_name='user_incidents', through='sharpcirt.UserRole', to=settings.AUTH_USER_MODEL),
        ),
    ]
