# Generated by Django 4.0.3 on 2025-01-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0014_alter_incident_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='user_roles',
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('INCIDENT_LEAD', 'Incident Lead'), ('RESPONDER', 'Responder'), ('READER', 'Reader')], max_length=20),
        ),
    ]
