# Generated by Django 4.0.3 on 2025-01-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0016_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='actions',
            field=models.ManyToManyField(related_name='tags', to='sharpcirt.action'),
        ),
        migrations.AddField(
            model_name='tag',
            name='iocs',
            field=models.ManyToManyField(related_name='tags', to='sharpcirt.genericioc'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tasks',
            field=models.ManyToManyField(related_name='tags', to='sharpcirt.task'),
        ),
    ]
