# Generated by Django 4.0.3 on 2025-01-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0017_tag_actions_tag_iocs_tag_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='iocs',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tasks',
        ),
    ]
