# Generated by Django 4.0.3 on 2025-01-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0018_remove_tag_actions_remove_tag_iocs_remove_tag_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='sharpcirt.tag'),
        ),
    ]
