# Generated by Django 4.0.3 on 2025-01-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0019_task_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='status',
        ),
        migrations.RemoveField(
            model_name='action',
            name='tag',
        ),
        migrations.AddField(
            model_name='genericioc',
            name='tags',
            field=models.ManyToManyField(related_name='ioc_tags', to='sharpcirt.tag'),
        ),
        migrations.AlterField(
            model_name='action',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(related_name='tags_task', to='sharpcirt.tag'),
        ),
        migrations.DeleteModel(
            name='IpAddress',
        ),
    ]
