# Generated by Django 4.0.3 on 2025-01-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0020_remove_action_status_remove_action_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='tags',
            field=models.ManyToManyField(related_name='action_tags', to='sharpcirt.tag'),
        ),
    ]
