# Generated by Django 4.0.3 on 2025-01-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0021_action_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='display_role',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='OPEN', max_length=20),
        ),
    ]
