# Generated by Django 4.0.3 on 2025-01-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0022_userrole_display_role_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='ending_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='observed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='starting_time',
            field=models.DateTimeField(null=True),
        ),
    ]
