# Generated by Django 4.0.3 on 2025-02-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0025_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='light_mode',
            field=models.CharField(default='light_mode', max_length=15),
        ),
    ]
