# Generated by Django 4.0.3 on 2025-03-10 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0026_user_light_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='business_impact',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='systems_impact',
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('external_reference', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('CONTINUOUS', 'Continuous'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_assignee', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_created', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='sharpcirt.incident')),
                ('tags', models.ManyToManyField(related_name='tags_impact', to='sharpcirt.tag')),
            ],
        ),
    ]
