# Generated by Django 4.0.3 on 2025-03-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0027_remove_incident_business_impact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impact',
            name='ending_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='impact',
            name='starting_time',
            field=models.DateTimeField(null=True),
        ),
    ]
