# Generated by Django 4.0.3 on 2025-03-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0028_impact_ending_time_impact_starting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='impact',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
