# Generated by Django 4.0.3 on 2025-03-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0029_impact_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='impact',
            name='type',
            field=models.CharField(choices=[('BUSINESS_IMPACT', 'Business impact'), ('REPUTATION', 'Reputation'), ('DATA_LOSS', 'Data Loss'), ('SYSTEMS_AVAILABILITY', 'Systems availability'), ('NOT_DEFINED', 'Not defined')], default='N/A', max_length=20),
        ),
    ]
