# Generated by Django 4.0.3 on 2025-03-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpcirt', '0030_impact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='impact',
            name='action',
            field=models.ManyToManyField(related_name='impacts', to='sharpcirt.action'),
        ),
    ]
